services:
- type: web
name: creative-studio-api
env: python
plan: free
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
autoDeploy: false
envVars:
- key: SECRET_KEY
generateValue: true